version: '3'

networks:
  net-mobxapp:
    external:
      name: net-mobxapp

services:
  modxapp-front:
    image: nginx
    ports:
      - 3045:3045
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/main-nginx.conf:/etc/nginx/nginx.conf
      #- ./ss.key:/etc/nginx/conf.d/ss.key
      #- ./ss.crt:/etc/nginx/conf.d/ss.crt
      - ../apps/frontend/build:/usr/share/nginx/html
    networks:
      - net-mobxapp
  
  mobxapp-back:
    image: node:14.15.4-alpine
    ports:
      - 3046:3046
    volumes:
      - ../apps/backend:/code

    # команда для запуска контейнера без старта сервиса (для установки модулей)
    #command: tail -f /dev/null
    # команда запуска сервиса
    command: sh -c "cd /code/ && yarn run start"
    networks:
      - net-mobxapp